### ISSUE TITLE
Random Key Value Pairs for AdOps ab Testing

### ISSUE THREAD

**Issue by albertgcsula** [wb-crowdfusion/wb-ads#18]
Need to setup a way to randomize key-value pairs per session that get passed through dfp for adops ab testing.

- establish 20 key values and setup buckets 1-20, for example ab1=[rand(1, 20)]&ab2=[rand(1, 20)],etc
- at session start, establish values and store in buckets
- this will go into display and custom params

**Comment by albertgcsula** [comment]
@oefada can you please code review this and test in browser. This script sets a cookie with name 'wbrandomab' with the value of 20 randomized values from 1-20. It will also set gpt custom parameters. You can see the code in action here http://ads-www.cfellentube.com/

**Comment by gdbrown** [comment]
this just got much simpler.  let's call it "abt", "wbabt" global, generates a rand value between 1 and 20.  one value.  this is now virtually the same as ppid.

no multiple buckets any more.

**Comment by gdbrown** [comment]
see here: https://jsfiddle.net/f41ghn5L/3/

even dist ^^

**Comment by gdbrown** [comment]
call the script file "abt.js" as well.
