### ISSUE TITLE
BUG: ABT value not getting passed to DFP from a "cold start"

### ISSUE THREAD

**Issue by jvasquez75** [wb-crowdfusion/wb-ads#22]
AdOps has noticed that if you have a user new to the site, the first time they load the page the "abt" value is not getting passed in the DFP call. Subsequent page loads the value gets passed fine.

This is a fairly urgent issue for AdOps because its skewing their A/B testing results.

**Comment by gdbrown** [comment]
The fix is ultra simple... google requires that the targeting param be a string.  on first load, it's an int.

change this:
```
googletag.pubads().setTargeting('abt', get());
```
to this:
```
googletag.pubads().setTargeting('abt', '' + get());
```
