### ISSUE TITLE
Enable GPT "SlotRenderEndedEvent"

### ISSUE THREAD

**Issue by jvasquez75** [wb-crowdfusion/wb-ads#5]
We have a need to know when an ad is actually filled to enable some view-ability features we are looking to add to TMZ.com. After speaking with Google they recommended adding call-backs using the 'SlotRenderEndedEvent' to run code once an ad is filled.

https://developers.google.com/doubleclick-gpt/reference#googletageventsslotrenderendedevent

**Comment by gdbrown** [comment]
moving to separate js project.
